export const PROFILE_UPDATING = 'PROFILE_UPDATING'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR'

export const ONLY_UPDATE_ROLES_UPDATING = 'ONLY_UPDATE_ROLES_UPDATING'
export const ONLY_UPDATE_ROLES_SUCCESS = 'ONLY_UPDATE_ROLES_SUCCESS'
export const ONLY_UPDATE_ROLES_ERROR = 'ONLY_UPDATE_ROLES_ERROR'
