export const PROFILE_PHOTOS_REQUESTING = 'PROFILE_PHOTOS_REQUESTING'
export const PROFILE_PHOTOS_REQUEST_SUCCESS = 'PROFILE_PHOTOS_REQUEST_SUCCESS'
export const PROFILE_PHOTOS_REQUEST_ERROR = 'PROFILE_PHOTOS_REQUEST_ERROR'

export const PROFILE_PHOTO_DELETING = 'PROFILE_PHOTO_DELETING'
export const PROFILE_PHOTO_DELETE_SUCCESS = 'PROFILE_PHOTO_DELETE_SUCCESS'
export const PROFILE_PHOTO_DELETE_ERROR = 'PROFILE_PHOTO_DELETE_ERROR'
