version: "3.3"
services:
    frontend-dev-b2b:
        build: .
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            CHOKIDAR_USEPOLLING: 'true'

        command: bash -c "yarn start"
        networks:
            - proxynetwork
networks:
    proxynetwork:
        external: true
