version: "3.3"
services:
    frontend:
        build: .
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            CHOKIDAR_USEPOLLING: 'true'

            #command: yarn start
        command: bash -c "yarn start"
        networks:
            - proxynetwork
networks:
    proxynetwork:
        external: true
