export const PAYMENT_METHODS_UPDATING = 'PAYMENT_METHODS_UPDATING'
export const PAYMENT_METHODS_UPDATE_SUCCESS = 'PAYMENT_METHODS_UPDATE_SUCCESS'
export const PAYMENT_METHODS_UPDATE_ERROR = 'PAYMENT_METHODS_UPDATE_ERROR'
