export const ADDRESS_UPDATING = 'ADDRESS_UPDATING'
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS'
export const ADDRESS_UPDATE_ERROR = 'ADDRESS_UPDATE_ERROR'

export const ADDRESS_DELETING = 'ADDRESS_DELETING'
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS'
export const ADDRESS_DELETE_ERROR = 'ADDRESS_DELETE_ERROR'
