export const CONTACT_UPDATING = 'CONTACT_UPDATING'
export const CONTACT_UPDATE_SUCCESS = 'CONTACT_UPDATE_SUCCESS'
export const CONTACT_UPDATE_ERROR = 'CONTACT_UPDATE_ERROR'

export const CONTACT_DELETING = 'CONTACT_DELETING'
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS'
export const CONTACT_DELETE_ERROR = 'CONTACT_DELETE_ERROR'
